### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by Excriyin** [CASPERg267/GF-Music#3]
Genius api doesnt work its saying type error undefined reading hits in node modules, it happens when you try to look at it from the dashboard. IT\t also doesnt work as a command says that im not in the same voice channel when I am actually mostyl all the commands say need to be in the same voice channel when i am

**Comment by CASPERg267** [comment]
Thanks you for submitting an issue, i ve fixed "need to be in the same voice channel" already but had some issues pushing the fix 😄 
should work fine now
for the dashboard lyrics works fine for me, will look into the issue with lyrics command

**Comment by Excriyin** [comment]
> Thanks you for submitting an issue, i ve fixed "need to be in the same voice channel" already but had some issues pushing the fix 😄 should work fine now for the dashboard lyrics works fine for me, will look into the issue with lyrics command

no problem! it was an issue with my key but i fixed it for the lyrics thanks for the fast reply

**Comment by Excriyin** [comment]
Btw the help  slash command doesnt show the commands, and idk if you disabled prefix but prefix commands doesnt work either

**Comment by CASPERg267** [comment]
Could you test with my last pushes, willing to close the issue for now, if you have any other issue feel free to reopen this issue or submit a new one.
