### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by aqajjif** [CASPERg267/GF-Music#8]
i'm getting this error when im trying to play music from the dashboard
![image](https://user-images.githubusercontent.com/98738008/205457055-9846e765-aa59-44dd-831f-6091a3d754ad.png)

**Comment by aqajjif** [comment]
also the music played but i can't access to the dashboard again until i restarted the bot 
![image](https://user-images.githubusercontent.com/98738008/205457138-3cd319e3-352f-4f34-a8b4-7f8e2280efc7.png)

**Comment by CASPERg267** [comment]
@aqajjif  Could you test with my last pushes?
also make sure your node version is 16 not 18 because the lyrics finder has problems with node v18

**Comment by aqajjif** [comment]
still the problem

**Comment by CASPERg267** [comment]
> still the problem

could you provide error stack, or any information i could use to produce the error?
